import type { TemplatesData } from './schemas';

export const mockTemplatesData: TemplatesData = {
  categories: [
    {
      slug: 'backend-applications',
      name: 'Backend Applications',
      description: 'API and service starters for FastAPI and similar Python backends.',
      details:
        'Use when the deliverable is an HTTP API or background worker — FastAPI for async APIs with OpenAPI docs.',
      labels: ['Backend', 'API', 'Python', 'FastAPI'],
    },
    {
      slug: 'ci',
      name: 'CI',
      description: 'Continuous integration and repository automation.',
      details: 'GitHub Actions, Dependabot, and related repository workflows.',
      labels: ['CI', 'GitHub', 'DevOps'],
    },
    {
      slug: 'containers',
      name: 'Containers',
      description: 'Docker and Compose packaging for the app.',
      details: 'Add when you want container images and compose stacks for the API.',
      labels: ['Docker', 'Compose', 'DevOps'],
    },
    {
      slug: 'database',
      name: 'Database',
      description: 'Database services and connection scaffolding.',
      details: 'Pair with the app when you need Postgres (or similar) locally/in compose.',
      labels: ['PostgreSQL', 'Database'],
    },
    {
      slug: 'editor',
      name: 'Editor',
      description: 'Editor and remote development ergonomics.',
      details: 'Dev Containers and related IDE integrations.',
      labels: ['DevContainer', 'VS Code'],
    },
    {
      slug: 'cli-applications',
      name: 'CLI Applications',
      description: 'Command-line tools and console scripts.',
      details: 'Use for Typer/Click CLIs and internal utilities shipped as entry points.',
      labels: ['CLI', 'Python', 'Typer'],
    },
    {
      slug: 'observability',
      name: 'Observability',
      description: 'Error tracking, metrics, and tracing integrations.',
      details: 'Add when you need production diagnostics such as Sentry.',
      labels: ['Observability', 'Sentry', 'Monitoring'],
    },
    {
      slug: 'security',
      name: 'Security',
      description: 'Authentication and authorization scaffolds.',
      details: 'JWT/session auth skeletons and related security helpers.',
      labels: ['Auth', 'JWT', 'Security'],
    },
    {
      slug: 'monorepo',
      name: 'Monorepo',
      description: 'Multi-package workspaces with shared tooling and one lockfile.',
      details:
        'Use when you need multiple libraries and apps in one repo — uv workspaces link members locally with a single virtual environment.',
      labels: ['Monorepo', 'uv', 'Workspace', 'Python'],
    },
  ],
  templates: [
    {
      slug: 'fastapi-starter',
      name: 'FastAPI Starter',
      description: 'Production-ready FastAPI API with uv, Ruff, pytest, mypy, pyright, and pydantic-settings',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/fastapi-starter',
      type: 'fastapi-backend',
      category: 'backend-applications',
      labels: ['FastAPI', 'API', 'Python', 'uv', 'Backend', 'Type Hints', 'mypy', 'pyright'],
    },
    {
      slug: 'cli-starter',
      name: 'CLI Starter',
      description: 'Typer CLI with uv, Ruff, pytest, and a console script entry point',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/cli-starter',
      type: 'cli-app',
      category: 'cli-applications',
      labels: ['CLI', 'Typer', 'Python', 'uv'],
    },
    {
      slug: 'celery-worker',
      name: 'Celery Worker',
      description: 'Celery worker with Redis defaults, pydantic-settings, and eager-mode tests',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/celery-worker',
      type: 'celery-worker',
      category: 'backend-applications',
      labels: ['Celery', 'Worker', 'Redis', 'Python', 'uv'],
    },
    {
      slug: 'django-api',
      name: 'Django API',
      description: 'Django + DRF API starter with uv, Ruff, pytest-django, and health probes',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/django-api',
      type: 'django-backend',
      category: 'backend-applications',
      labels: ['Django', 'DRF', 'API', 'Python', 'uv'],
    },
    {
      slug: 'uv-workspace-starter',
      name: 'uv Workspace Starter',
      description:
        'Python monorepo using uv workspaces: shared packages/ libraries and apps/ deployables with one lockfile, Ruff, Pyright, and pytest',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/uv-workspace-starter',
      type: 'uv-workspace',
      category: 'monorepo',
      labels: ['Monorepo', 'uv', 'Workspace', 'Python', 'Typer'],
    },
  ],
  extensions: [
    {
      slug: 'github-setup',
      name: 'GitHub Setup',
      description: 'GitHub Actions CI, MegaLinter, Danger PR review, todo-to-issue, Dependabot, and issue/PR templates',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-github-setup',
      type: ['celery-worker', 'cli-app', 'django-backend', 'fastapi-backend', 'uv-workspace'],
      category: 'ci',
      labels: ['GitHub', 'CI', 'DevOps', 'MegaLinter', 'Danger'],
    },
    {
      slug: 'fastapi-docker',
      name: 'FastAPI Docker',
      description: 'Dockerfile and Compose for uvicorn FastAPI apps under app/',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-docker',
      type: ['fastapi-backend'],
      category: 'containers',
      labels: ['Docker', 'DevOps', 'Container', 'FastAPI'],
    },
    {
      slug: 'django-docker',
      name: 'Django Docker',
      description: 'Dockerfile and Compose for Django/gunicorn under apps/ + config/',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/django-docker',
      type: ['django-backend'],
      category: 'containers',
      labels: ['Docker', 'DevOps', 'Container', 'Django'],
    },
    {
      slug: 'celery-docker',
      name: 'Celery Docker',
      description: 'Dockerfile with Celery worker CMD for the celery-worker template',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/celery-docker',
      type: ['celery-worker'],
      category: 'containers',
      labels: ['Docker', 'DevOps', 'Container', 'Celery'],
    },
    {
      slug: 'postgres',
      name: 'Postgres',
      description: 'PostgreSQL service under docker/postgres/compose.yml plus env examples',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-postgres',
      type: ['celery-worker', 'django-backend', 'fastapi-backend'],
      category: 'database',
      labels: ['PostgreSQL', 'Database', 'Docker'],
    },
    {
      slug: 'development-container',
      name: 'Development Container',
      description: 'VS Code Dev Container with Python 3.12 and uv',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-devcontainer',
      type: ['celery-worker', 'cli-app', 'django-backend', 'fastapi-backend', 'uv-workspace'],
      category: 'editor',
      labels: ['DevContainer', 'VS Code', 'uv'],
    },
    {
      slug: 'fastapi-sqlalchemy',
      name: 'FastAPI SQLAlchemy',
      description: 'SQLAlchemy 2.x session helpers and Alembic migrations for FastAPI',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-sqlalchemy',
      type: ['fastapi-backend'],
      category: 'database',
      labels: ['SQLAlchemy', 'Alembic', 'ORM', 'Database'],
    },
    {
      slug: 'fastapi-redis',
      name: 'FastAPI Redis',
      description: 'Redis client helper and local Compose service for FastAPI',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-redis',
      type: ['fastapi-backend'],
      category: 'database',
      labels: ['Redis', 'Cache', 'Queue'],
    },
    {
      slug: 'fastapi-sentry',
      name: 'FastAPI Sentry',
      description: 'Sentry SDK for FastAPI with env-driven init helper',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-sentry',
      type: ['fastapi-backend'],
      category: 'observability',
      labels: ['Sentry', 'Observability', 'Errors'],
    },
    {
      slug: 'fastapi-auth-jwt',
      name: 'FastAPI Auth JWT',
      description: 'JWT auth feature skeleton with password hashing helpers',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-auth-jwt',
      type: ['fastapi-backend'],
      category: 'security',
      labels: ['Auth', 'JWT', 'Security'],
    },
  ],
};

// Helper function to get fallback data if API fails
export function getFallbackData(): TemplatesData {
  return mockTemplatesData;
}
