import type { TemplatesData } from './schemas';

export const mockTemplatesData: TemplatesData = {
  categories: [
    {
      slug: 'backend-applications',
      name: 'Backend Applications',
      description: 'API and service starters for FastAPI and similar Python backends.',
      details:
        'Use when the deliverable is an HTTP API or background worker — FastAPI for async APIs with OpenAPI docs.',
      labels: ['Backend', 'API', 'Python', 'FastAPI'],
    },
    {
      slug: 'ci',
      name: 'CI',
      description: 'Continuous integration and repository automation.',
      details: 'GitHub Actions, Dependabot, and related repository workflows.',
      labels: ['CI', 'GitHub', 'DevOps'],
    },
    {
      slug: 'containers',
      name: 'Containers',
      description: 'Docker and Compose packaging for the app.',
      details: 'Add when you want container images and compose stacks for the API.',
      labels: ['Docker', 'Compose', 'DevOps'],
    },
    {
      slug: 'database',
      name: 'Database',
      description: 'Database services and connection scaffolding.',
      details: 'Pair with the app when you need Postgres (or similar) locally/in compose.',
      labels: ['PostgreSQL', 'Database'],
    },
    {
      slug: 'editor',
      name: 'Editor',
      description: 'Editor and remote development ergonomics.',
      details: 'Dev Containers and related IDE integrations.',
      labels: ['DevContainer', 'VS Code'],
    },
    {
      slug: 'cli-applications',
      name: 'CLI Applications',
      description: 'Command-line tools and console scripts.',
      details: 'Use for Typer/Click CLIs and internal utilities shipped as entry points.',
      labels: ['CLI', 'Python', 'Typer'],
    },
    {
      slug: 'observability',
      name: 'Observability',
      description: 'Error tracking, metrics, and tracing integrations.',
      details: 'Add when you need production diagnostics such as Sentry.',
      labels: ['Observability', 'Sentry', 'Monitoring'],
    },
    {
      slug: 'security',
      name: 'Security',
      description: 'Authentication and authorization scaffolds.',
      details: 'JWT/session auth skeletons and related security helpers.',
      labels: ['Auth', 'JWT', 'Security'],
    },
    {
      slug: 'monorepo',
      name: 'Monorepo',
      description: 'Multi-package workspaces with shared tooling and one lockfile.',
      details:
        'Use when you need multiple libraries and apps in one repo — uv workspaces link members locally with a single virtual environment.',
      labels: ['Monorepo', 'uv', 'Workspace', 'Python'],
    },
    {
      slug: 'ai-ml-applications',
      name: 'AI/ML Applications',
      description: 'FastAPI AI and ML capability extensions.',
      details: 'Add when you need LLM-backed chat, retrieval, or agent endpoints on a FastAPI starter.',
      labels: ['AI', 'ML', 'LangChain', 'FastAPI'],
    },
    {
      slug: 'mlops',
      name: 'MLOps',
      description: 'MLOps framework starters and training/serving pipelines.',
      details: 'CPU-first sklearn/pytorch/tensorflow topologies with MLflow-friendly defaults.',
      labels: ['MLOps', 'sklearn', 'MLflow', 'Python'],
    },
  ],
  templates: [
    {
      slug: 'fastapi-starter',
      name: 'FastAPI Starter',
      description:
        'Production-ready FastAPI API with feature-based layout, uv, Ruff, pytest, mypy, pyright, and pydantic-settings. The reference CPA backend template.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/fastapi-starter',
      type: 'fastapi-backend',
      category: 'backend-applications',
      labels: ['FastAPI', 'API', 'Python', 'uv', 'Backend', 'Type Hints', 'mypy', 'pyright'],
    },
    {
      slug: 'cli-starter',
      name: 'CLI Starter',
      description:
        'Typer CLI with multi-command layout, uv, Ruff, pytest, and a console script entry point. Best for internal tools and shippable CLIs.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/cli-starter',
      type: 'cli-app',
      category: 'cli-applications',
      labels: ['CLI', 'Typer', 'Python', 'uv'],
    },
    {
      slug: 'celery-worker',
      name: 'Celery Worker',
      description:
        'Celery worker with modular tasks, Redis defaults, pydantic-settings, and eager-mode tests. Choose it for background jobs outside the HTTP process.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/celery-worker',
      type: 'celery-worker',
      category: 'backend-applications',
      labels: ['Celery', 'Worker', 'Redis', 'Python', 'uv'],
    },
    {
      slug: 'django-api',
      name: 'Django API',
      description:
        "Django + DRF API with feature apps, OpenAPI-friendly health probes, uv, Ruff, and pytest-django. Use when you want Django's ORM and admin with a clean API layout.",
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/django-api',
      type: 'django-backend',
      category: 'backend-applications',
      labels: ['Django', 'DRF', 'API', 'Python', 'uv'],
    },
    {
      slug: 'uv-workspace-starter',
      name: 'uv Workspace Starter',
      description:
        'Python monorepo using uv workspaces: shared packages/ libraries and apps/ deployables with one lockfile, Ruff, Pyright, and pytest.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/uv-workspace-starter',
      type: 'uv-workspace',
      category: 'monorepo',
      labels: ['Monorepo', 'uv', 'Workspace', 'Python', 'Typer'],
    },
    {
      slug: 'mlops-sklearn-starter',
      name: 'MLOps sklearn Starter',
      description:
        'CPU-first sklearn MLOps pipeline with YAML configs, step architecture, local MLflow, and batch/FastAPI serving.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=templates/mlops-sklearn-starter',
      type: 'mlops-sklearn',
      category: 'mlops',
      labels: ['MLOps', 'sklearn', 'MLflow', 'Python', 'uv'],
    },
  ],
  extensions: [
    {
      slug: 'github-setup',
      name: 'GitHub Setup',
      description:
        'GitHub Actions CI, MegaLinter, Danger PR review, todo-to-issue, Dependabot, and issue/PR templates. Use for any CPA template that lives on GitHub.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-github-setup',
      type: ['celery-worker', 'cli-app', 'django-backend', 'fastapi-backend', 'mlops-sklearn', 'uv-workspace'],
      category: 'ci',
      labels: ['GitHub', 'CI', 'DevOps', 'MegaLinter', 'Danger'],
    },
    {
      slug: 'development-container',
      name: 'Development Container',
      description: 'VS Code Dev Container with Python 3.12 and uv for consistent editor environments across stacks.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-devcontainer',
      type: ['celery-worker', 'cli-app', 'django-backend', 'fastapi-backend', 'uv-workspace'],
      category: 'editor',
      labels: ['DevContainer', 'VS Code', 'uv'],
    },
    {
      slug: 'postgres',
      name: 'Postgres',
      description:
        'PostgreSQL 16 Compose service under docker/postgres/ plus env examples. Infra-only — does not write application ORM code.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-postgres',
      type: ['celery-worker', 'django-backend', 'fastapi-backend'],
      category: 'database',
      labels: ['PostgreSQL', 'Database', 'Docker'],
    },
    {
      slug: 'fastapi-cors',
      name: 'FastAPI CORS',
      description: 'CORS middleware helper for FastAPI (no-op without CORS_ORIGINS).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-cors',
      type: ['fastapi-backend'],
      category: 'security',
      labels: ['CORS', 'Security', 'FastAPI', 'Middleware'],
    },
    {
      slug: 'fastapi-docker',
      name: 'FastAPI Docker',
      description:
        'Dockerfile and Compose for FastAPI (uvicorn app.main:app). Reach for it when containerizing the FastAPI starter.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-docker',
      type: ['fastapi-backend'],
      category: 'containers',
      labels: ['Docker', 'FastAPI', 'Container'],
    },
    {
      slug: 'django-docker',
      name: 'Django Docker',
      description: 'Dockerfile and Compose for Django (runserver / gunicorn config.wsgi). Use with django-api.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/django-docker',
      type: ['django-backend'],
      category: 'containers',
      labels: ['Docker', 'Django', 'Container'],
    },
    {
      slug: 'celery-docker',
      name: 'Celery Docker',
      description:
        'Dockerfile and Compose for a Celery worker plus Redis broker. Pair with a reachable BROKER_URL (Compose sets redis://redis:6379/0).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/celery-docker',
      type: ['celery-worker'],
      category: 'containers',
      labels: ['Docker', 'Celery', 'Container'],
    },
    {
      slug: 'flower-docker',
      name: 'Flower (Celery monitoring)',
      description:
        'Flower monitoring for Celery tasks — Compose stack with Redis, worker, and Flower dashboard (port 5555).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/flower-docker',
      type: ['celery-worker'],
      category: 'observability',
      labels: ['Flower', 'Celery', 'Monitoring', 'Observability'],
    },
    {
      slug: 'fastapi-sqlalchemy',
      name: 'FastAPI SQLAlchemy',
      description: 'SQLAlchemy 2.x session helpers and Alembic migrations for FastAPI (writes app/db/).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-sqlalchemy',
      type: ['fastapi-backend'],
      category: 'database',
      labels: ['SQLAlchemy', 'Alembic', 'ORM', 'FastAPI'],
    },
    {
      slug: 'fastapi-redis',
      name: 'FastAPI Redis',
      description: 'Redis client helper under app/core plus a local Redis Compose service for FastAPI apps.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-redis',
      type: ['fastapi-backend'],
      category: 'database',
      labels: ['Redis', 'Cache', 'FastAPI'],
    },
    {
      slug: 'fastapi-sentry',
      name: 'FastAPI Sentry',
      description: 'Sentry SDK helper for FastAPI with env-driven init (no-op without SENTRY_DSN).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-sentry',
      type: ['fastapi-backend'],
      category: 'observability',
      labels: ['Sentry', 'Observability', 'FastAPI'],
    },
    {
      slug: 'fastapi-auth-jwt',
      name: 'FastAPI Auth JWT',
      description: 'JWT auth feature skeleton under app/features/auth for FastAPI starters.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-auth-jwt',
      type: ['fastapi-backend'],
      category: 'security',
      labels: ['Auth', 'JWT', 'FastAPI', 'Security'],
    },
    {
      slug: 'pre-commit',
      name: 'Pre-commit',
      description: 'Local quality gates with Ruff, YAML validation, and whitespace checks for every CPA template.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/all-pre-commit',
      type: ['celery-worker', 'cli-app', 'django-backend', 'fastapi-backend', 'uv-workspace'],
      category: 'ci',
      labels: ['Pre-commit', 'Quality', 'Git Hooks'],
    },
    {
      slug: 'fastapi-opentelemetry',
      name: 'FastAPI OpenTelemetry',
      description:
        'OpenTelemetry tracing and logging hooks for FastAPI projects, useful for local debugging and observability setup.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-opentelemetry',
      type: ['fastapi-backend'],
      category: 'observability',
      labels: ['OpenTelemetry', 'Tracing', 'Observability'],
    },
    {
      slug: 'fastapi-rate-limit',
      name: 'FastAPI Rate Limit',
      description: 'Rate limiting helper using slowapi (in-memory by default, Redis-ready).',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-rate-limit',
      type: ['fastapi-backend'],
      category: 'security',
      labels: ['Rate Limit', 'Security', 'FastAPI'],
    },
    {
      slug: 'fastapi-mlflow-tracing',
      name: 'FastAPI MLflow Tracing',
      description:
        'Generic MLflow tracing infrastructure for FastAPI. Disabled by default; exposes reusable primitives for future extensions.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-mlflow-tracing',
      type: ['fastapi-backend'],
      category: 'observability',
      labels: ['MLflow', 'Tracing', 'Observability', 'FastAPI'],
    },
    {
      slug: 'fastapi-rag-pgvector',
      name: 'FastAPI RAG pgvector',
      description:
        'Foundational RAG data layer using pgvector. Provides agnostic chunking, embedding generation, and vector retrieval services.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-rag-pgvector',
      type: ['fastapi-backend'],
      category: 'ai-ml-applications',
      labels: ['RAG', 'AI', 'pgvector', 'FastAPI', 'PostgreSQL'],
    },
    {
      slug: 'fastapi-ai-chat',
      name: 'FastAPI AI Chat',
      description:
        "Minimal /chat endpoint backed by LangChain's BaseChatModel. Mock provider by default — drop in a real provider via init_chat_model() with no interface change.",
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/fastapi-ai-chat',
      type: ['fastapi-backend'],
      category: 'ai-ml-applications',
      labels: ['LangChain', 'AI', 'Chat', 'FastAPI'],
    },
    {
      slug: 'django-spectacular',
      name: 'Django Spectacular',
      description: 'OpenAPI 3 schema generation and Swagger UI for Django REST Framework.',
      url: 'https://github.com/Create-Python-App/cpa-templates?subdir=extensions/django-spectacular',
      type: ['django-backend'],
      category: 'observability',
      labels: ['Django', 'OpenAPI', 'Swagger', 'DRF'],
    },
  ],
};

// Helper function to get fallback data if API fails
export function getFallbackData(): TemplatesData {
  return mockTemplatesData;
}
